accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'accounts'

urlpatterns = [
    path('create/', views.CreateAccountView.as_view(), name='create'),

    path('login/', auth_views.LoginView.as_view(
        template_name='login.html'
    ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='logout.html'
    ), name='logout'),
    path('change-password', auth_views.PasswordChangeView.as_view(
        # success_url='/',
        template_name='password_change.html'
    ), name='password-change'),
]

folder_organizer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', RedirectView.as_view(pattern_name='folders:folder-list')),
    path('accounts/', include('accounts.urls')),
    path('folders/', include('folders.urls')),

    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

folders/urls.py
from django.urls import path

from . import views


app_name = 'folders'

urlpatterns = [
    path('', views.FolderListView.as_view(), name='folder-list'),

    path('add-folder/', views.AddFolderView.as_view(), name='add-folder'),
    path('<int:pk>/update-folder/', views.UpdateFolderView.as_view(), name='update-folder'),  # noqa
    path('<int:pk>/delete-folder/', views.DeleteFolderView.as_view(), name='delete-folder'),  # noqa

    path('<int:pk>/missing/', views.MissingListView.as_view(), name='missing-list'),  # noqa
    path('<int:pk>/add-missing/', views.AddMissingView.as_view(), name='add-missing'),  # noqa
    path('<int:pk>/update-missing/', views.UpdateMissingView.as_view(), name='update-missing'),  # noqa
    path('<int:pk>/delete-missing/', views.DeleteMissingView.as_view(), name='delete-missing'),  # noqa
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

folders/models.py
from django.db import models

from accounts.models import User


class Folder(models.Model):
    name = models.CharField(max_length=250, default='Incomplete')
    serie = models.CharField(max_length=10, default='Incomplete')
    from_date = models.DateField(null=True, blank=True, default=None)
    to_date = models.DateField(null=True, blank=True, default=None)
    from_guide = models.CharField(max_length=15, blank=True, default=None)
    to_guide = models.CharField(max_length=15, blank=True, default=None)
    code = models.CharField(max_length=10, default='Incomplete')
    is_full = models.BooleanField(default=False)
    color = models.CharField(max_length=10, default='white')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.code


class Missing(models.Model):
    guide = models.CharField(max_length=25)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)

    def __str__(self):
        return self.guide

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import User


class CreateUserForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2'
        ]

folders/forms.py
from django import forms

from .models import Folder, Missing


class AddFolderForm(forms.ModelForm):
    class Meta():
        model = Folder
        fields = [
            'owner',
            'name',
            'serie',
            'from_date',
            'to_date',
            'from_guide',
            'to_guide',
            'code',
        ]


class AddMissingForm(forms.ModelForm):
    class Meta():
        model = Missing
        fields = [
            'folder',
            'guide',
        ]

accounts/views.py
from django.views.generic.edit import CreateView

from .models import User
from .forms import CreateUserForm


class CreateAccountView(CreateView):
    model = User
    form_class = CreateUserForm
    template_name = 'create_account.html'
    success_url = '/accounts/login/'

folders/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

from .forms import AddFolderForm, AddMissingForm
from .models import Folder, Missing


class FolderListView(LoginRequiredMixin, ListView):
    model = Folder
    context_object_name = 'all_folders'
    template_name = 'folder_list.html'
    paginate_by = 12

    def get_queryset(self):
        all_folders = Folder.objects.filter(
            owner_id=self.request.user.id
        )

        return all_folders


class AddFolderView(LoginRequiredMixin, CreateView):
    model = Folder
    form_class = AddFolderForm
    template_name = 'add_folder.html'
    success_url = '/folders/'


class UpdateFolderView(LoginRequiredMixin, UpdateView):
    model = Folder
    fields = [
        'name',
        'serie',
        'from_date',
        'to_date',
        'from_guide',
        'to_guide',
        'code',
    ]
    template_name = 'update_folder.html'
    success_url = '/folders/'


class DeleteFolderView(LoginRequiredMixin, DeleteView):
    model = Folder
    template_name = 'delete_folder.html'
    success_url = '/folders/'


class MissingListView(ListView):
    model = Missing
    context_object_name = 'all_missing'
    template_name = 'missing_list.html'

    def get_queryset(self):
        all_missing = Missing.objects.filter(
            folder=self.kwargs['pk']
        )

        return all_missing


class AddMissingView(LoginRequiredMixin, CreateView):
    model = Missing
    form_class = AddMissingForm
    template_name = 'add_missing.html'

    def get_success_url(self):

        return reverse(
            'folders:missing-list',
            kwargs={'pk': self.kwargs['pk']}
        )


class UpdateMissingView(LoginRequiredMixin, UpdateView):
    model = Missing
    fields = [
        'guide',
    ]
    template_name = 'update_missing.html'

    def get_success_url(self):
        self.missing = self.get_object().folder
        self.folder = Folder.objects.get(code=self.missing)

        return reverse(
            'folders:missing-list',
            kwargs={'pk': self.folder.id}
        )


class DeleteMissingView(LoginRequiredMixin, DeleteView):
    model = Missing

    def delete(self, *args, **kwargs):
        self.missing = self.get_object().folder
        self.folder = Folder.objects.get(code=self.missing)

        return super(DeleteMissingView, self).delete(*args, **kwargs)

    def get_success_url(self):

        return reverse(
            'folders:missing-list',
            kwargs={'pk': self.folder.id}
        )

accounts/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="https://img.icons8.com/nolan/64/folder-invoices.png" type="image/x-icon">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block body_main %}
    {% endblock body_main %}
</body>
</html>

accounts/templates/create_account.html
{% extends 'base/base.html' %}

{% block title %}Create account{% endblock %}

{% block body_main %}
    <main class="grid grid-cols-1 max-w-md m-5 mx-auto p-2">
        <form method="post" class="flex flex-col p-3 items-center border border-blue-500 rounded-lg">
            {% csrf_token %}

            <div class="flex flex-col p-3 justify-items border-b">
                <label for="username" class="m-2">
                    Username:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="text" name="{{ form.username.html_name }}" id="username">
                </label>

                <label for="email" class="m-2">
                    Email:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="email" name="{{ form.email.html_name }}" id="email">
                </label>

                <label for="password1" class="m-2">
                    Password:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="password" name="{{ form.password1.html_name }}" id="password1">
                </label>

                <label for="password2" class="m-2">
                    Repeat password:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="password" name="{{ form.password2.html_name }}" id="password2">
                </label>
            </div>

            <div class="flex justify-between w-full px-3">
                <a href="{% url 'accounts:login' %}" class="border border-blue-500 rounded-lg my-5 px-3 py-2">
                    Login
                </a>

                <button class="bg-green-500 text-white border border-green-500 rounded-lg my-5 px-3 py-2" type="submit">
                    Register
                </button>
            </div>
        </form>
    </main>
{% endblock body_main %}

accounts/templates/login.html
{% extends 'base/base.html' %}

{% block title %}Login{% endblock %}

{% block body_main %}
    <main class="grid grid-cols-1 max-w-md m-5 mx-auto p-2">
        <form method="post" class="flex flex-col p-3 items-center border border-blue-500 rounded-lg">
            {% csrf_token %}

            <div class="flex flex-col p-3 justify-items border-b">
                <label for="username" class="m-2">
                    Username:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="text" id="username" name="{{ form.username.html_name }}">
                </label>

                <label for="password" class="m-2">
                    Password:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="password" id="password" name="{{ form.password.html_name }}">
                </label>
            </div>

            <div class="flex justify-between w-full px-3">
                <a href="{% url 'accounts:create' %}" class="border border-blue-500 rounded-lg my-5 px-3 py-2">
                    Register
                </a>

                <button class="bg-green-500 text-white border border-green-500 rounded-lg my-5 px-3 py-2" type="submit">
                    Login
                </button>
            </div>
        </form>
    </main>
{% endblock body_main %}

accounts/templates/logout.html
{% extends 'base/base.html' %}

{% block title %}Create account{% endblock %}

{% block body_main %}
    <div>
        Logout template
    </div>
{% endblock body_main %}

accounts/templates/password_change.html
{% extends 'base/base.html' %}

{% block title %}Change password{% endblock %}

{% block body_main %}
    <main class="grid grid-cols-1 max-w-md m-5 mx-auto p-2">
        <form method="post" class="flex flex-col p-3 items-center border border-blue-500 rounded-lg">
            {% csrf_token %}

            <div class="flex flex-col p-3 justify-items border-b">
                <label for="username" class="m-2">
                    Password:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="text" id="username" name="{{ form.username.html_name }}">
                </label>

                <label for="password" class="m-2">
                    Password:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="password" id="password" name="{{ form.password.html_name }}">
                </label>
            </div>

            <button class="bg-green-500 text-white border border-green-500 rounded-lg my-5 px-3 py-2" type="submit">
                Login
            </button>
        </form>
    </main>
{% endblock body_main %}

folders/templates/add_folder.html
{% extends 'base/folders_base.html' %}

{% block title %}Add folder{% endblock %}

{% block body_main %}
    <nav class="flex justify-between border-b-2 m-3 my-5 px-3 pb-3">
        <div>
            <a class="" href="{% url 'accounts:logout' %}">
                Logout
            </a>
        </div>
        <div>
            <a class="border border-blue-500 rounded-lg p-1" href="{% url 'folders:folder-list' %}">
                Back
            </a>
        </div>
    </nav>

    <main class="grid grid-cols-1 max-w-md m-5 mx-auto p-2">
        <form class="flex flex-col p-3 items-center border border-blue-500 rounded-lg" method="post">
            {% csrf_token %}

            <input type="hidden" value="{{ request.user.id }}" name="{{ form.owner.html_name }}">

            <div class="flex flex-col p-3 justify-items border-b">
                <label for="name" class="m-2">
                    Name:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="text" name="{{ form.name.html_name }}" id="name">
                </label>

                <label for="serie" class="m-2">
                    Serie:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="text" name="{{ form.serie.html_name }}" id="serie">
                </label>

                <label for="from_date" class="m-2">
                    From date:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="date" name="{{ form.from_date.html_name }}" id="from_date">
                </label>

                <label for="to_date" class="m-2">
                    To date:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="date" name="{{ form.to_date.html_name }}" id="to_date">
                </label>

                <label for="from_guide" class="m-2">
                    From guide:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="text" name="{{ form.from_guide.html_name }}" id="from_guide">
                </label>

                <label for="to_guide" class="m-2">
                    To guide:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="text" name="{{ form.to_guide.html_name }}" id="to_guide">
                </label>

                <label for="code" class="m-2">
                    Code:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="text" name="{{ form.code.html_name }}" id="code">
                </label>
            </div>

            <button class="bg-green-500 text-white border border-green-500 rounded-lg my-5 px-3 py-2" type="submit">
                Add folder
            </button>
        </form>
    </main>
{% endblock body_main %}

folders/templates/add_missing.html
{% extends 'base/folders_base.html' %}

{% block title %}Add missing{% endblock %}

{% block body_main %}
    <nav class="flex justify-between border-b-2 m-3 my-5 px-3 pb-3">
        <div>
            <a class="" href="{% url 'accounts:logout' %}">
                Logout
            </a>
        </div>
        <div>
            <a class="border border-blue-500 rounded-lg p-1" href="{% url 'folders:missing-list' view.kwargs.pk %}">
                Back
            </a>
        </div>
    </nav>

    <main class="grid grid-cols-1 max-w-md m-5 mx-auto p-2">
        <div class="flex flex-col p-3 items-center border border-blue-500 rounded-lg">
            <div class="flex flex-col p-3 justify-items">
                <form method="post">
                    {% csrf_token %}

                    <input type="hidden" name="folder" value="{{ view.kwargs.pk }}">

                    <label class="mx-3" for="guide">
                        Guide:
                        <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" name="guide" id="guide" type="text">
                    </label>

                    <button class="bg-green-500 text-white border border-green-500 rounded-lg mt-1 px-3 py-1" type="submit">
                        Add
                    </button>
                </form>
            </div>
        </div>
    </main>
{% endblock body_main %}

folders/templates/base/folders_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="https://img.icons8.com/nolan/64/folder-invoices.png" type="image/x-icon">
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="static">
    {% block body_main %}
    {% endblock body_main %}
</body>
</html>

folders/templates/delete_folder.html
{% extends 'base/folders_base.html' %}

{% block title %}Folder organizer{% endblock %}

{% block body_main %}
    <nav class="flex justify-between border-b-2 m-3 my-5 px-3 pb-3">
        <div>
            <a class="" href="{% url 'accounts:logout' %}">
                Logout
            </a>
        </div>
        <div>
            <a class="border border-blue-500 rounded-lg p-1" href="{% url 'folders:folder-list' %}">
                Cancel
            </a>
        </div>
    </nav>

    <main class="grid grid-cols-1 max-w-md m-5 mx-auto p-2">
        <form class="flex flex-col p-3 items-center border border-blue-500 rounded-lg" method="post">
            {% csrf_token %}

            <div class="flex flex-col p-3 justify-items border-b">
                <div class="mb-2">
                    <p>Are you sure you want to delete?</p>
                </div>

                <div class="text-center">
                    Folder code: {{ object }}
                </div>
            </div>

            <button class="bg-red-500 text-white border border-red-500 rounded-lg my-5 px-3 py-2" type="submit">
                Delete
            </button>
        </form>
    </main>
{% endblock body_main %}

folders/templates/folder_list.html
{% extends 'base/folders_base.html' %}

{% block title %}Folder organizer{% endblock %}

{% block body_main %}
    <nav class="flex justify-between border-b-2 m-3 my-5 px-3 pb-3">
        <div>
            {% if request.user.is_authenticated %}
                <a class="" href="{% url 'accounts:logout' %}">
                    Logout
                </a>
            {% else %}
                Registrate o inicia sesión primero
            {% endif %}
        </div>
        <div class="">
            <a class="border border-green-500 rounded-lg p-1" href="{% url 'folders:add-folder' %}">
                Add folder
            </a>
        </div>
    </nav>
    
    <main class="grid gap-4 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-4 max-w-5xl m-5 mx-auto p-2">
        {% for folder in all_folders %}
            <div class="grid-rows-2 p-3">
                <div class="text-center grid grid-cols-1 border rounded-lg border-gray-500 border-b">
                    <div class="p-2">
                        {{ folder.name }}
                    </div>
                    <div class="p-2">
                        {{ folder.serie }}
                    </div>
                    <div class="p-2">
                        {{ folder.from_date|date:'M-Y'|default:'---' }} to {{ folder.to_date|date:'M-Y'|default:'---' }}
                    </div>
                    <div class="p-2">
                        {{ folder.from_guide }} to {{ folder.to_guide }}
                    </div>
                    <div class="p-2">
                        {{ folder.code }}
                    </div>
                </div>

                <div class="flex justify-evenly inline-block mt-2 pb-1">
                    <div class="text-sm justify-center">
                        <a class="border border-yellow-400 rounded-lg p-1" href="{% url 'folders:missing-list' folder.id %}" type="button">
                            Missing
                        </a>
                    </div>
                    <div class="text-sm justify-center">
                        <a class="border border-blue-400 rounded-lg p-1" href="{% url 'folders:update-folder' folder.id %}" type="button">
                            Update
                        </a>
                    </div>
                    <div class="text-sm justify-center">
                        <a class="border border-red-400 rounded-lg p-1" href="{% url 'folders:delete-folder' folder.id %}" type="button">
                            Delete
                        </a>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="flex justify-center md:col-span-2 lg:col-span-4">
                Add new folders with the right top button!
            </div>
        {% endfor %}
    </main>

    <footer class="static bottom-0 w-full">
        <div class="flex justify-between m-3 p-2">
            {% if page_obj.has_previous %}
                <a class="text-white bg-indigo-500 border border-indigo-500 rounded-lg p-1" href="?page={{ page_obj.previous_page_number }}">
                    Previus
                </a>
            {% else %}
                <a class="text-white bg-indigo-500 border border-indigo-500 rounded-lg p-1" href="#">
                    Previus
                </a>
            {% endif %}

            {% if page_obj.has_next %}
                <a class="text-white bg-indigo-500 border border-indigo-500 rounded-lg p-1" href="?page={{ page_obj.next_page_number }}">
                    Next
                </a>
            {% else %}
                <a class="text-white bg-indigo-500 border border-indigo-500 rounded-lg p-1" href="#">
                    Next
                </a>
            {% endif %}
        </div>
    </footer>
{% endblock body_main %}

folders/templates/missing_list.html
{% extends 'base/folders_base.html' %}

{% block title %}Missing{% endblock %}

{% block body_main %}
    <nav class="flex justify-between border-b-2 m-3 my-5 px-3 pb-3">
        <div>
            <a class="" href="{% url 'accounts:logout' %}">
                Logout
            </a>
        </div>
        <div>
            <a class="border border-blue-500 rounded-lg p-1" href="{% url 'folders:folder-list' %}">
                Back
            </a>
        </div>
    </nav>

    <main class="grid grid-cols-1 max-w-md m-5 mx-auto p-2">
        <div class="flex flex-col p-3 items-center border border-blue-500 rounded-lg">
            <div class="flex flex-col justify-items">
                {% for missing in all_missing %}
                    <div class="border-b p-2">
                        <form class="flex" action="{% url 'folders:update-missing' missing.id %}" id="update-form" method="post">
                            {% csrf_token %}

                            <label class="block p-2" for="guide">
                                Guide:
                                <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent w-2/3 px-1" type="text" name="guide" id="guide" value="{{ missing }}">
                            </label>

                            <button class="text-sm bg-blue-500 text-white border border-blue-500 rounded-lg my-1 p-1" class="text-right" type="submit">
                                Update
                            </button>
                        </form>

                        <form class="flex flex-row-reverse" action="{% url 'folders:delete-missing' missing.id %}" id="delete_form" method="post">
                            {% csrf_token %}

                            <button class="text-sm border border-red-500 rounded-lg p-1" type="submit">
                                Delete
                            </button>
                        </form>
                    </div>
                {% empty %}
                    <div class="m-3">
                        <p>Empty</p>
                    </div>
                {% endfor %}
            </div>

            <a class="bg-green-500 text-white border border-green-500 rounded-lg mt-3 px-3 py-2" href="{% url 'folders:add-missing' view.kwargs.pk %}" type="button">
                Add
            </a>
        </div>
    </main>
{% endblock body_main %}

folders/templates/update_folder.html
{% extends 'base/folders_base.html' %}

{% block title %}Update folder{% endblock %}

{% block body_main %}
    <nav class="flex justify-between border-b-2 m-3 my-5 px-3 pb-3">
        <div>
            <a class="" href="{% url 'accounts:logout' %}">
                Logout
            </a>
        </div>
        <div>
            <a class="border border-blue-500 rounded-lg p-1" href="{% url 'folders:folder-list' %}">
                Back
            </a>
        </div>
    </nav>

    <main class="grid grid-cols-1 max-w-md m-5 mx-auto p-2">
        <form class="flex flex-col p-3 items-center border border-blue-500 rounded-lg" method="post">
            {% csrf_token %}

            {% comment %} <input type="hidden" value="{{ view.kwargs.pk }}" name="{{ form.owner.html_name }}"> {% endcomment %}

            <div class="flex flex-col p-3 justify-items border-b">
                <label for="name" class="m-2">
                    Name:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="text" name="{{ form.name.html_name }}" id="name" value="{{ object.name }}">
                </label>

                <label for="serie" class="m-2">
                    Serie:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="text" name="{{ form.serie.html_name }}" id="serie" value="{{ object.serie }}">
                </label>

                <label for="from_date" class="m-2">
                    From date:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="date" name="{{ form.from_date.html_name }}" id="from_date" value="{{ object.from_date|date:'yy-m-d' }}">
                </label>

                <label for="to_date" class="m-2">
                    To date:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="date" name="{{ form.to_date.html_name }}" id="to_date" value="{{ object.to_date|date:'yy-m-d' }}">
                </label>

                <label for="from_guide" class="m-2">
                    From guide:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="text" name="{{ form.from_guide.html_name }}" id="from_guide" value="{{ object.from_guide }}">
                </label>

                <label for="to_guide" class="m-2">
                    To guide:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="text" name="{{ form.to_guide.html_name }}" id="to_guide" value="{{ object.to_guide }}">
                </label>

                <label for="code" class="m-2">
                    Code:
                    <input class="border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent px-1" type="text" name="{{ form.code.html_name }}" id="code" value="{{ object.code }}">
                </label>
            </div>

            <button class="bg-green-500 text-white border border-green-500 rounded-lg my-5 px-3 py-2" type="submit">
                Update
            </button>
        </form>
    </main>
{% endblock body_main %}

folders/templates/update_missing.html
{% extends 'base/folders_base.html' %}

{% block title %}Update missing{% endblock %}

{% block body_main %}
    <nav class="flex justify-between border-b-2 m-3 my-5 px-3 pb-3">
        <div>
            <a class="" href="{% url 'accounts:logout' %}">
                Logout
            </a>
        </div>
        <div>
            <a class="border border-blue-500 rounded-lg p-1" href="{% url 'folders:folder-list' %}">Back</a>
        </div>
    </nav>

    <main>
        
    </main>
{% endblock body_main %}